//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gigya.Umbraco._6._2._1.umbraco.Plugins.Gigya
{


    public partial class DashboardIntro
    {
    }
}
